# Generated by Django 5.0 on 2024-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_joiners'),
    ]

    operations = [
        migrations.CreateModel(
            name='donaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('emaild', models.EmailField(max_length=254, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
