# Generated by Django 5.0 on 2024-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donaters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donaters',
            old_name='address',
            new_name='addressd',
        ),
        migrations.RenameField(
            model_name='donaters',
            old_name='amount',
            new_name='amountd',
        ),
        migrations.RenameField(
            model_name='donaters',
            old_name='name',
            new_name='named',
        ),
        migrations.AddField(
            model_name='donaters',
            name='payment_signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
